#
# 2013 April 17
#
# The author disclaims copyright to this source code.  In place of
# a legal notice, here is a blessing:
#
#    May you do good and not evil.
#    May you find forgiveness for yourself and forgive others.
#    May you share freely, never taking more than you give.
#
#***********************************************************************
# This is automatically generated by MAKE_SYMBOL_VECTOR. DO NOT EDIT!!!
#
	.text
	.align 8
.globl	_SQLITE3_SET_AUTHORIZER
_SQLITE3_SET_AUTHORIZER:
	.word	0xff
	jmp	_sqlite3_set_authorizer+2
.globl	_SQLITE3_BACKUP_FINISH
_SQLITE3_BACKUP_FINISH:
	.word	0xff
	jmp	_sqlite3_backup_finish+2
.globl	_SQLITE3_BACKUP_INIT
_SQLITE3_BACKUP_INIT:
	.word	0xff
	jmp	_sqlite3_backup_init+2
.globl	_SQLITE3_BACKUP_PAGECOUNT
_SQLITE3_BACKUP_PAGECOUNT:
	.word	0xff
	jmp	_sqlite3_backup_pagecount+2
.globl	_SQLITE3_BACKUP_REMAINING
_SQLITE3_BACKUP_REMAINING:
	.word	0xff
	jmp	_sqlite3_backup_remaining+2
.globl	_SQLITE3_BACKUP_STEP
_SQLITE3_BACKUP_STEP:
	.word	0xff
	jmp	_sqlite3_backup_step+2
.globl	_SQLITE3_ENABLE_SHARED_CACHE
_SQLITE3_ENABLE_SHARED_CACHE:
	.word	0xff
	jmp	_sqlite3_enable_shared_cache+2
.globl	_SQLITE3_COMPLETE
_SQLITE3_COMPLETE:
	.word	0xff
	jmp	_sqlite3_complete+2
.globl	_SQLITE3_COMPILEOPTION_GET
_SQLITE3_COMPILEOPTION_GET:
	.word	0xff
	jmp	_sqlite3_compileoption_get+2
.globl	_SQLITE3_COMPILEOPTION_USED
_SQLITE3_COMPILEOPTION_USED:
	.word	0xff
	jmp	_sqlite3_compileoption_used+2
.globl	_SQLITE3_EXEC
_SQLITE3_EXEC:
	.word	0xff
	jmp	_sqlite3_exec+2
.globl	_SQLITE3_AUTO_EXTENSION
_SQLITE3_AUTO_EXTENSION:
	.word	0xff
	jmp	_sqlite3_auto_extension+2
.globl	_SQLITE3_ENABLE_LOAD_EXTENSION
_SQLITE3_ENABLE_LOAD_EXTENSION:
	.word	0xff
	jmp	_sqlite3_enable_load_extension+2
.globl	_SQLITE3_LOAD_EXTENSION
_SQLITE3_LOAD_EXTENSION:
	.word	0xff
	jmp	_sqlite3_load_extension+2
.globl	_SQLITE3_RESET_AUTO_EXTENSION
_SQLITE3_RESET_AUTO_EXTENSION:
	.word	0xff
	jmp	_sqlite3_reset_auto_extension+2
.globl	_SQLITE3_BUSY_HANDLER
_SQLITE3_BUSY_HANDLER:
	.word	0xff
	jmp	_sqlite3_busy_handler+2
.globl	_SQLITE3_BUSY_TIMEOUT
_SQLITE3_BUSY_TIMEOUT:
	.word	0xff
	jmp	_sqlite3_busy_timeout+2
.globl	_SQLITE3_CHANGES
_SQLITE3_CHANGES:
	.word	0xff
	jmp	_sqlite3_changes+2
.globl	_SQLITE3_CLOSE
_SQLITE3_CLOSE:
	.word	0xff
	jmp	_sqlite3_close+2
.globl	_SQLITE3_CLOSE_V2
_SQLITE3_CLOSE_V2:
	.word	0xff
	jmp	_sqlite3_close_v2+2
.globl	_SQLITE3_COLLATION_NEEDED
_SQLITE3_COLLATION_NEEDED:
	.word	0xff
	jmp	_sqlite3_collation_needed+2
.globl	_SQLITE3_COMMIT_HOOK
_SQLITE3_COMMIT_HOOK:
	.word	0xff
	jmp	_sqlite3_commit_hook+2
.globl	_SQLITE3_CONFIG
_SQLITE3_CONFIG:
	.word	0xff
	jmp	_sqlite3_config+2
.globl	_SQLITE3_CREATE_COLLATION
_SQLITE3_CREATE_COLLATION:
	.word	0xff
	jmp	_sqlite3_create_collation+2
.globl	_SQLITE3_CREATE_COLLATION_V2
_SQLITE3_CREATE_COLLATION_V2:
	.word	0xff
	jmp	_sqlite3_create_collation_v2+2
.globl	_SQLITE3_CREATE_FUNCTION
_SQLITE3_CREATE_FUNCTION:
	.word	0xff
	jmp	_sqlite3_create_function+2
.globl	_SQLITE3_CREATE_FUNCTION_V2
_SQLITE3_CREATE_FUNCTION_V2:
	.word	0xff
	jmp	_sqlite3_create_function_v2+2
.globl	_SQLITE3_DATA_DIRECTORY
_SQLITE3_DATA_DIRECTORY:
	.word	0xff
	jmp	_sqlite3_data_directory+2
.globl	_SQLITE3_DB_CONFIG
_SQLITE3_DB_CONFIG:
	.word	0xff
	jmp	_sqlite3_db_config+2
.globl	_SQLITE3_DB_FILENAME
_SQLITE3_DB_FILENAME:
	.word	0xff
	jmp	_sqlite3_db_filename+2
.globl	_SQLITE3_DB_MUTEX
_SQLITE3_DB_MUTEX:
	.word	0xff
	jmp	_sqlite3_db_mutex+2
.globl	_SQLITE3_DB_READONLY
_SQLITE3_DB_READONLY:
	.word	0xff
	jmp	_sqlite3_db_readonly+2
.globl	_SQLITE3_DB_RELEASE_MEMORY
_SQLITE3_DB_RELEASE_MEMORY:
	.word	0xff
	jmp	_sqlite3_db_release_memory+2
.globl	_SQLITE3_ERRCODE
_SQLITE3_ERRCODE:
	.word	0xff
	jmp	_sqlite3_errcode+2
.globl	_SQLITE3_ERRMSG
_SQLITE3_ERRMSG:
	.word	0xff
	jmp	_sqlite3_errmsg+2
.globl	_SQLITE3_ERRSTR
_SQLITE3_ERRSTR:
	.word	0xff
	jmp	_sqlite3_errstr+2
.globl	_SQLITE3_EXTENDED_ERRCODE
_SQLITE3_EXTENDED_ERRCODE:
	.word	0xff
	jmp	_sqlite3_extended_errcode+2
.globl	_SQLITE3_EXTENDED_RESULT_CODES
_SQLITE3_EXTENDED_RESULT_CODES:
	.word	0xff
	jmp	_sqlite3_extended_result_codes+2
.globl	_SQLITE3_FILE_CONTROL
_SQLITE3_FILE_CONTROL:
	.word	0xff
	jmp	_sqlite3_file_control+2
.globl	_SQLITE3_GET_AUTOCOMMIT
_SQLITE3_GET_AUTOCOMMIT:
	.word	0xff
	jmp	_sqlite3_get_autocommit+2
.globl	_SQLITE3_GLOBAL_RECOVER
_SQLITE3_GLOBAL_RECOVER:
	.word	0xff
	jmp	_sqlite3_global_recover+2
.globl	_SQLITE3_INITIALIZE
_SQLITE3_INITIALIZE:
	.word	0xff
	jmp	_sqlite3_initialize+2
.globl	_SQLITE3_INTERRUPT
_SQLITE3_INTERRUPT:
	.word	0xff
	jmp	_sqlite3_interrupt+2
.globl	_SQLITE3_LAST_INSERT_ROWID
_SQLITE3_LAST_INSERT_ROWID:
	.word	0xff
	jmp	_sqlite3_last_insert_rowid+2
.globl	_SQLITE3_LIBVERSION
_SQLITE3_LIBVERSION:
	.word	0xff
	jmp	_sqlite3_libversion+2
.globl	_SQLITE3_LIBVERSION_NUMBER
_SQLITE3_LIBVERSION_NUMBER:
	.word	0xff
	jmp	_sqlite3_libversion_number+2
.globl	_SQLITE3_LIMIT
_SQLITE3_LIMIT:
	.word	0xff
	jmp	_sqlite3_limit+2
.globl	_SQLITE3_OPEN
_SQLITE3_OPEN:
	.word	0xff
	jmp	_sqlite3_open+2
.globl	_SQLITE3_OPEN_V2
_SQLITE3_OPEN_V2:
	.word	0xff
	jmp	_sqlite3_open_v2+2
.globl	_SQLITE3_OVERLOAD_FUNCTION
_SQLITE3_OVERLOAD_FUNCTION:
	.word	0xff
	jmp	_sqlite3_overload_function+2
.globl	_SQLITE3_PROFILE
_SQLITE3_PROFILE:
	.word	0xff
	jmp	_sqlite3_profile+2
.globl	_SQLITE3_PROGRESS_HANDLER
_SQLITE3_PROGRESS_HANDLER:
	.word	0xff
	jmp	_sqlite3_progress_handler+2
.globl	_SQLITE3_ROLLBACK_HOOK
_SQLITE3_ROLLBACK_HOOK:
	.word	0xff
	jmp	_sqlite3_rollback_hook+2
.globl	_SQLITE3_SHUTDOWN
_SQLITE3_SHUTDOWN:
	.word	0xff
	jmp	_sqlite3_shutdown+2
.globl	_SQLITE3_SLEEP
_SQLITE3_SLEEP:
	.word	0xff
	jmp	_sqlite3_sleep+2
.globl	_SQLITE3_SOURCEID
_SQLITE3_SOURCEID:
	.word	0xff
	jmp	_sqlite3_sourceid+2
.globl	_SQLITE3_TABLE_COLUMN_METADATA
_SQLITE3_TABLE_COLUMN_METADATA:
	.word	0xff
	jmp	_sqlite3_table_column_metadata+2
.globl	_SQLITE3_TEMP_DIRECTORY
_SQLITE3_TEMP_DIRECTORY:
	.word	0xff
	jmp	_sqlite3_temp_directory+2
.globl	_SQLITE3_TEST_CONTROL
_SQLITE3_TEST_CONTROL:
	.word	0xff
	jmp	_sqlite3_test_control+2
.globl	_SQLITE3_THREAD_CLEANUP
_SQLITE3_THREAD_CLEANUP:
	.word	0xff
	jmp	_sqlite3_thread_cleanup+2
.globl	_SQLITE3_THREADSAFE
_SQLITE3_THREADSAFE:
	.word	0xff
	jmp	_sqlite3_threadsafe+2
.globl	_SQLITE3_TOTAL_CHANGES
_SQLITE3_TOTAL_CHANGES:
	.word	0xff
	jmp	_sqlite3_total_changes+2
.globl	_SQLITE3_TRACE
_SQLITE3_TRACE:
	.word	0xff
	jmp	_sqlite3_trace+2
.globl	_SQLITE3_UPDATE_HOOK
_SQLITE3_UPDATE_HOOK:
	.word	0xff
	jmp	_sqlite3_update_hook+2
.globl	_SQLITE3_URI_BOOLEAN
_SQLITE3_URI_BOOLEAN:
	.word	0xff
	jmp	_sqlite3_uri_boolean+2
.globl	_SQLITE3_URI_INT64
_SQLITE3_URI_INT64:
	.word	0xff
	jmp	_sqlite3_uri_int64+2
.globl	_SQLITE3_URI_PARAMETER
_SQLITE3_URI_PARAMETER:
	.word	0xff
	jmp	_sqlite3_uri_parameter+2
.globl	_SQLITE3_VERSION
_SQLITE3_VERSION:
	.word	0xff
	jmp	_sqlite3_version+2
.globl	_SQLITE3_WAL_AUTOCHECKPOINT
_SQLITE3_WAL_AUTOCHECKPOINT:
	.word	0xff
	jmp	_sqlite3_wal_autocheckpoint+2
.globl	_SQLITE3_WAL_CHECKPOINT
_SQLITE3_WAL_CHECKPOINT:
	.word	0xff
	jmp	_sqlite3_wal_checkpoint+2
.globl	_SQLITE3_WAL_CHECKPOINT_V2
_SQLITE3_WAL_CHECKPOINT_V2:
	.word	0xff
	jmp	_sqlite3_wal_checkpoint_v2+2
.globl	_SQLITE3_WAL_HOOK
_SQLITE3_WAL_HOOK:
	.word	0xff
	jmp	_sqlite3_wal_hook+2
.globl	_SQLITE3_FREE
_SQLITE3_FREE:
	.word	0xff
	jmp	_sqlite3_free+2
.globl	_SQLITE3_MALLOC
_SQLITE3_MALLOC:
	.word	0xff
	jmp	_sqlite3_malloc+2
.globl	_SQLITE3_MEMORY_ALARM
_SQLITE3_MEMORY_ALARM:
	.word	0xff
	jmp	_sqlite3_memory_alarm+2
.globl	_SQLITE3_MEMORY_HIGHWATER
_SQLITE3_MEMORY_HIGHWATER:
	.word	0xff
	jmp	_sqlite3_memory_highwater+2
.globl	_SQLITE3_MEMORY_USED
_SQLITE3_MEMORY_USED:
	.word	0xff
	jmp	_sqlite3_memory_used+2
.globl	_SQLITE3_REALLOC
_SQLITE3_REALLOC:
	.word	0xff
	jmp	_sqlite3_realloc+2
.globl	_SQLITE3_RELEASE_MEMORY
_SQLITE3_RELEASE_MEMORY:
	.word	0xff
	jmp	_sqlite3_release_memory+2
.globl	_SQLITE3_SOFT_HEAP_LIMIT
_SQLITE3_SOFT_HEAP_LIMIT:
	.word	0xff
	jmp	_sqlite3_soft_heap_limit+2
.globl	_SQLITE3_SOFT_HEAP_LIMIT64
_SQLITE3_SOFT_HEAP_LIMIT64:
	.word	0xff
	jmp	_sqlite3_soft_heap_limit64+2
.globl	_SQLITE3_MUTEX_ALLOC
_SQLITE3_MUTEX_ALLOC:
	.word	0xff
	jmp	_sqlite3_mutex_alloc+2
.globl	_SQLITE3_MUTEX_ENTER
_SQLITE3_MUTEX_ENTER:
	.word	0xff
	jmp	_sqlite3_mutex_enter+2
.globl	_SQLITE3_MUTEX_FREE
_SQLITE3_MUTEX_FREE:
	.word	0xff
	jmp	_sqlite3_mutex_free+2
.globl	_SQLITE3_MUTEX_LEAVE
_SQLITE3_MUTEX_LEAVE:
	.word	0xff
	jmp	_sqlite3_mutex_leave+2
.globl	_SQLITE3_MUTEX_TRY
_SQLITE3_MUTEX_TRY:
	.word	0xff
	jmp	_sqlite3_mutex_try+2
.globl	_SQLITE3_VFS_FIND
_SQLITE3_VFS_FIND:
	.word	0xff
	jmp	_sqlite3_vfs_find+2
.globl	_SQLITE3_VFS_REGISTER
_SQLITE3_VFS_REGISTER:
	.word	0xff
	jmp	_sqlite3_vfs_register+2
.globl	_SQLITE3_VFS_UNREGISTER
_SQLITE3_VFS_UNREGISTER:
	.word	0xff
	jmp	_sqlite3_vfs_unregister+2
.globl	_SQLITE3_OS_END
_SQLITE3_OS_END:
	.word	0xff
	jmp	_sqlite3_os_end+2
.globl	_SQLITE3_OS_INIT
_SQLITE3_OS_INIT:
	.word	0xff
	jmp	_sqlite3_os_init+2
.globl	_SQLITE3_PREPARE
_SQLITE3_PREPARE:
	.word	0xff
	jmp	_sqlite3_prepare+2
.globl	_SQLITE3_PREPARE_V2
_SQLITE3_PREPARE_V2:
	.word	0xff
	jmp	_sqlite3_prepare_v2+2
.globl	_SQLITE3_LOG
_SQLITE3_LOG:
	.word	0xff
	jmp	_sqlite3_log+2
.globl	_SQLITE3_MPRINTF
_SQLITE3_MPRINTF:
	.word	0xff
	jmp	_sqlite3_mprintf+2
.globl	_SQLITE3_SNPRINTF
_SQLITE3_SNPRINTF:
	.word	0xff
	jmp	_sqlite3_snprintf+2
.globl	_SQLITE3_VMPRINTF
_SQLITE3_VMPRINTF:
	.word	0xff
	jmp	_sqlite3_vmprintf+2
.globl	_SQLITE3_VSNPRINTF
_SQLITE3_VSNPRINTF:
	.word	0xff
	jmp	_sqlite3_vsnprintf+2
.globl	_SQLITE3_RANDOMNESS
_SQLITE3_RANDOMNESS:
	.word	0xff
	jmp	_sqlite3_randomness+2
.globl	_SQLITE3_DB_STATUS
_SQLITE3_DB_STATUS:
	.word	0xff
	jmp	_sqlite3_db_status+2
.globl	_SQLITE3_STATUS
_SQLITE3_STATUS:
	.word	0xff
	jmp	_sqlite3_status+2
.globl	_SQLITE3_FREE_TABLE
_SQLITE3_FREE_TABLE:
	.word	0xff
	jmp	_sqlite3_free_table+2
.globl	_SQLITE3_GET_TABLE
_SQLITE3_GET_TABLE:
	.word	0xff
	jmp	_sqlite3_get_table+2
.globl	_SQLITE3_STRICMP
_SQLITE3_STRICMP:
	.word	0xff
	jmp	_sqlite3_stricmp+2
.globl	_SQLITE3_STRNICMP
_SQLITE3_STRNICMP:
	.word	0xff
	jmp	_sqlite3_strnicmp+2
.globl	_SQLITE3_VALUE_NUMERIC_TYPE
_SQLITE3_VALUE_NUMERIC_TYPE:
	.word	0xff
	jmp	_sqlite3_value_numeric_type+2
.globl	_SQLITE3_AGGREGATE_CONTEXT
_SQLITE3_AGGREGATE_CONTEXT:
	.word	0xff
	jmp	_sqlite3_aggregate_context+2
.globl	_SQLITE3_AGGREGATE_COUNT
_SQLITE3_AGGREGATE_COUNT:
	.word	0xff
	jmp	_sqlite3_aggregate_count+2
.globl	_SQLITE3_BIND_BLOB
_SQLITE3_BIND_BLOB:
	.word	0xff
	jmp	_sqlite3_bind_blob+2
.globl	_SQLITE3_BIND_DOUBLE
_SQLITE3_BIND_DOUBLE:
	.word	0xff
	jmp	_sqlite3_bind_double+2
.globl	_SQLITE3_BIND_INT
_SQLITE3_BIND_INT:
	.word	0xff
	jmp	_sqlite3_bind_int+2
.globl	_SQLITE3_BIND_INT64
_SQLITE3_BIND_INT64:
	.word	0xff
	jmp	_sqlite3_bind_int64+2
.globl	_SQLITE3_BIND_NULL
_SQLITE3_BIND_NULL:
	.word	0xff
	jmp	_sqlite3_bind_null+2
.globl	_SQLITE3_BIND_PARAMETER_COUNT
_SQLITE3_BIND_PARAMETER_COUNT:
	.word	0xff
	jmp	_sqlite3_bind_parameter_count+2
.globl	_SQLITE3_BIND_PARAMETER_INDEX
_SQLITE3_BIND_PARAMETER_INDEX:
	.word	0xff
	jmp	_sqlite3_bind_parameter_index+2
.globl	_SQLITE3_BIND_PARAMETER_NAME
_SQLITE3_BIND_PARAMETER_NAME:
	.word	0xff
	jmp	_sqlite3_bind_parameter_name+2
.globl	_SQLITE3_BIND_TEXT
_SQLITE3_BIND_TEXT:
	.word	0xff
	jmp	_sqlite3_bind_text+2
.globl	_SQLITE3_BIND_VALUE
_SQLITE3_BIND_VALUE:
	.word	0xff
	jmp	_sqlite3_bind_value+2
.globl	_SQLITE3_BIND_ZEROBLOB
_SQLITE3_BIND_ZEROBLOB:
	.word	0xff
	jmp	_sqlite3_bind_zeroblob+2
.globl	_SQLITE3_CLEAR_BINDINGS
_SQLITE3_CLEAR_BINDINGS:
	.word	0xff
	jmp	_sqlite3_clear_bindings+2
.globl	_SQLITE3_COLUMN_BLOB
_SQLITE3_COLUMN_BLOB:
	.word	0xff
	jmp	_sqlite3_column_blob+2
.globl	_SQLITE3_COLUMN_BYTES
_SQLITE3_COLUMN_BYTES:
	.word	0xff
	jmp	_sqlite3_column_bytes+2
.globl	_SQLITE3_COLUMN_BYTES16
_SQLITE3_COLUMN_BYTES16:
	.word	0xff
	jmp	_sqlite3_column_bytes16+2
.globl	_SQLITE3_COLUMN_COUNT
_SQLITE3_COLUMN_COUNT:
	.word	0xff
	jmp	_sqlite3_column_count+2
.globl	_SQLITE3_COLUMN_DATABASE_NAME
_SQLITE3_COLUMN_DATABASE_NAME:
	.word	0xff
	jmp	_sqlite3_column_database_name+2
.globl	_SQLITE3_COLUMN_DECLTYPE
_SQLITE3_COLUMN_DECLTYPE:
	.word	0xff
	jmp	_sqlite3_column_decltype+2
.globl	_SQLITE3_COLUMN_DOUBLE
_SQLITE3_COLUMN_DOUBLE:
	.word	0xff
	jmp	_sqlite3_column_double+2
.globl	_SQLITE3_COLUMN_INT
_SQLITE3_COLUMN_INT:
	.word	0xff
	jmp	_sqlite3_column_int+2
.globl	_SQLITE3_COLUMN_INT64
_SQLITE3_COLUMN_INT64:
	.word	0xff
	jmp	_sqlite3_column_int64+2
.globl	_SQLITE3_COLUMN_NAME
_SQLITE3_COLUMN_NAME:
	.word	0xff
	jmp	_sqlite3_column_name+2
.globl	_SQLITE3_COLUMN_ORIGIN_NAME
_SQLITE3_COLUMN_ORIGIN_NAME:
	.word	0xff
	jmp	_sqlite3_column_origin_name+2
.globl	_SQLITE3_COLUMN_TABLE_NAME
_SQLITE3_COLUMN_TABLE_NAME:
	.word	0xff
	jmp	_sqlite3_column_table_name+2
.globl	_SQLITE3_COLUMN_TEXT
_SQLITE3_COLUMN_TEXT:
	.word	0xff
	jmp	_sqlite3_column_text+2
.globl	_SQLITE3_COLUMN_TYPE
_SQLITE3_COLUMN_TYPE:
	.word	0xff
	jmp	_sqlite3_column_type+2
.globl	_SQLITE3_COLUMN_VALUE
_SQLITE3_COLUMN_VALUE:
	.word	0xff
	jmp	_sqlite3_column_value+2
.globl	_SQLITE3_CONTEXT_DB_HANDLE
_SQLITE3_CONTEXT_DB_HANDLE:
	.word	0xff
	jmp	_sqlite3_context_db_handle+2
.globl	_SQLITE3_DATA_COUNT
_SQLITE3_DATA_COUNT:
	.word	0xff
	jmp	_sqlite3_data_count+2
.globl	_SQLITE3_DB_HANDLE
_SQLITE3_DB_HANDLE:
	.word	0xff
	jmp	_sqlite3_db_handle+2
.globl	_SQLITE3_EXPIRED
_SQLITE3_EXPIRED:
	.word	0xff
	jmp	_sqlite3_expired+2
.globl	_SQLITE3_FINALIZE
_SQLITE3_FINALIZE:
	.word	0xff
	jmp	_sqlite3_finalize+2
.globl	_SQLITE3_GET_AUXDATA
_SQLITE3_GET_AUXDATA:
	.word	0xff
	jmp	_sqlite3_get_auxdata+2
.globl	_SQLITE3_NEXT_STMT
_SQLITE3_NEXT_STMT:
	.word	0xff
	jmp	_sqlite3_next_stmt+2
.globl	_SQLITE3_RESET
_SQLITE3_RESET:
	.word	0xff
	jmp	_sqlite3_reset+2
.globl	_SQLITE3_RESULT_BLOB
_SQLITE3_RESULT_BLOB:
	.word	0xff
	jmp	_sqlite3_result_blob+2
.globl	_SQLITE3_RESULT_DOUBLE
_SQLITE3_RESULT_DOUBLE:
	.word	0xff
	jmp	_sqlite3_result_double+2
.globl	_SQLITE3_RESULT_ERROR
_SQLITE3_RESULT_ERROR:
	.word	0xff
	jmp	_sqlite3_result_error+2
.globl	_SQLITE3_RESULT_ERROR_CODE
_SQLITE3_RESULT_ERROR_CODE:
	.word	0xff
	jmp	_sqlite3_result_error_code+2
.globl	_SQLITE3_RESULT_ERROR_NOMEM
_SQLITE3_RESULT_ERROR_NOMEM:
	.word	0xff
	jmp	_sqlite3_result_error_nomem+2
.globl	_SQLITE3_RESULT_ERROR_TOOBIG
_SQLITE3_RESULT_ERROR_TOOBIG:
	.word	0xff
	jmp	_sqlite3_result_error_toobig+2
.globl	_SQLITE3_RESULT_INT
_SQLITE3_RESULT_INT:
	.word	0xff
	jmp	_sqlite3_result_int+2
.globl	_SQLITE3_RESULT_INT64
_SQLITE3_RESULT_INT64:
	.word	0xff
	jmp	_sqlite3_result_int64+2
.globl	_SQLITE3_RESULT_NULL
_SQLITE3_RESULT_NULL:
	.word	0xff
	jmp	_sqlite3_result_null+2
.globl	_SQLITE3_RESULT_TEXT
_SQLITE3_RESULT_TEXT:
	.word	0xff
	jmp	_sqlite3_result_text+2
.globl	_SQLITE3_RESULT_VALUE
_SQLITE3_RESULT_VALUE:
	.word	0xff
	jmp	_sqlite3_result_value+2
.globl	_SQLITE3_RESULT_ZEROBLOB
_SQLITE3_RESULT_ZEROBLOB:
	.word	0xff
	jmp	_sqlite3_result_zeroblob+2
.globl	_SQLITE3_SET_AUXDATA
_SQLITE3_SET_AUXDATA:
	.word	0xff
	jmp	_sqlite3_set_auxdata+2
.globl	_SQLITE3_STEP
_SQLITE3_STEP:
	.word	0xff
	jmp	_sqlite3_step+2
.globl	_SQLITE3_STMT_BUSY
_SQLITE3_STMT_BUSY:
	.word	0xff
	jmp	_sqlite3_stmt_busy+2
.globl	_SQLITE3_STMT_READONLY
_SQLITE3_STMT_READONLY:
	.word	0xff
	jmp	_sqlite3_stmt_readonly+2
.globl	_SQLITE3_STMT_STATUS
_SQLITE3_STMT_STATUS:
	.word	0xff
	jmp	_sqlite3_stmt_status+2
.globl	_SQLITE3_TRANSFER_BINDINGS
_SQLITE3_TRANSFER_BINDINGS:
	.word	0xff
	jmp	_sqlite3_transfer_bindings+2
.globl	_SQLITE3_USER_DATA
_SQLITE3_USER_DATA:
	.word	0xff
	jmp	_sqlite3_user_data+2
.globl	_SQLITE3_VALUE_BLOB
_SQLITE3_VALUE_BLOB:
	.word	0xff
	jmp	_sqlite3_value_blob+2
.globl	_SQLITE3_VALUE_BYTES
_SQLITE3_VALUE_BYTES:
	.word	0xff
	jmp	_sqlite3_value_bytes+2
.globl	_SQLITE3_VALUE_BYTES16
_SQLITE3_VALUE_BYTES16:
	.word	0xff
	jmp	_sqlite3_value_bytes16+2
.globl	_SQLITE3_VALUE_DOUBLE
_SQLITE3_VALUE_DOUBLE:
	.word	0xff
	jmp	_sqlite3_value_double+2
.globl	_SQLITE3_VALUE_INT
_SQLITE3_VALUE_INT:
	.word	0xff
	jmp	_sqlite3_value_int+2
.globl	_SQLITE3_VALUE_INT64
_SQLITE3_VALUE_INT64:
	.word	0xff
	jmp	_sqlite3_value_int64+2
.globl	_SQLITE3_VALUE_TEXT
_SQLITE3_VALUE_TEXT:
	.word	0xff
	jmp	_sqlite3_value_text+2
.globl	_SQLITE3_VALUE_TYPE
_SQLITE3_VALUE_TYPE:
	.word	0xff
	jmp	_sqlite3_value_type+2
.globl	_SQLITE3_SQL
_SQLITE3_SQL:
	.word	0xff
	jmp	_sqlite3_sql+2
.globl	_SQLITE3_BLOB_BYTES
_SQLITE3_BLOB_BYTES:
	.word	0xff
	jmp	_sqlite3_blob_bytes+2
.globl	_SQLITE3_BLOB_CLOSE
_SQLITE3_BLOB_CLOSE:
	.word	0xff
	jmp	_sqlite3_blob_close+2
.globl	_SQLITE3_BLOB_OPEN
_SQLITE3_BLOB_OPEN:
	.word	0xff
	jmp	_sqlite3_blob_open+2
.globl	_SQLITE3_BLOB_READ
_SQLITE3_BLOB_READ:
	.word	0xff
	jmp	_sqlite3_blob_read+2
.globl	_SQLITE3_BLOB_REOPEN
_SQLITE3_BLOB_REOPEN:
	.word	0xff
	jmp	_sqlite3_blob_reopen+2
.globl	_SQLITE3_BLOB_WRITE
_SQLITE3_BLOB_WRITE:
	.word	0xff
	jmp	_sqlite3_blob_write+2
.globl	_SQLITE3_CREATE_MODULE
_SQLITE3_CREATE_MODULE:
	.word	0xff
	jmp	_sqlite3_create_module+2
.globl	_SQLITE3_CREATE_MODULE_V2
_SQLITE3_CREATE_MODULE_V2:
	.word	0xff
	jmp	_sqlite3_create_module_v2+2
.globl	_SQLITE3_DECLARE_VTAB
_SQLITE3_DECLARE_VTAB:
	.word	0xff
	jmp	_sqlite3_declare_vtab+2
.globl	_SQLITE3_VTAB_CONFIG
_SQLITE3_VTAB_CONFIG:
	.word	0xff
	jmp	_sqlite3_vtab_config+2
.globl	_SQLITE3_VTAB_ON_CONFLICT
_SQLITE3_VTAB_ON_CONFLICT:
	.word	0xff
	jmp	_sqlite3_vtab_on_conflict+2
